import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

const CLI = join(process.cwd(), "src/cli/main.ts");

let cacheHome: string;
let roots: string[];

function run(args: string[], expectFailure = false): string {
  try {
    return execFileSync(
      process.execPath,
      ["--import", "tsx", CLI, ...args],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        env: { ...process.env, HOME: cacheHome },
        stdio: "pipe",
      },
    );
  } catch (error) {
    if (!expectFailure) throw error;
    const failure = error as { stdout?: string; stderr?: string };
    return `${failure.stdout ?? ""}${failure.stderr ?? ""}`;
  }
}

function project(): string {
  const root = mkdtempSync(join(tmpdir(), "sonde-doccli-"));
  roots.push(root);
  mkdirSync(join(root, "src/a"), { recursive: true });
  mkdirSync(join(root, "src/b"), { recursive: true });
  writeFileSync(
    join(root, "tsconfig.json"),
    JSON.stringify({ compilerOptions: { moduleResolution: "bundler" } }),
  );
  writeFileSync(
    join(root, "src/b/util.ts"),
    "export function helper() { return 1; }\n",
  );
  writeFileSync(
    join(root, "src/a/main.ts"),
    "import { helper } from '../b/util.js';\n" +
      "export function run() { return helper(); }\n",
  );
  return root;
}

beforeEach(() => {
  cacheHome = mkdtempSync(join(tmpdir(), "sonde-doc-home-"));
  roots = [];
});

afterEach(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
  rmSync(cacheHome, { recursive: true, force: true });
});

describe("sonde doc", () => {
  it("refuses without an index rather than writing an empty document", () => {
    const root = project();
    const output = run(["doc", root], true);
    expect(output).toMatch(/sonde index/);
    expect(existsSync(join(root, "ARCHITECTURE.md"))).toBe(false);
  }, 120_000);

  it("writes ARCHITECTURE.md after indexing", () => {
    const root = project();
    run(["index", root]);
    run(["doc", root]);
    const doc = readFileSync(join(root, "ARCHITECTURE.md"), "utf8");
    expect(doc).toContain("# Architecture");
    expect(doc).toContain("src/a");
  }, 120_000);

  it("regenerates byte-identically", () => {
    const root = project();
    run(["index", root]);
    run(["doc", root]);
    const first = readFileSync(join(root, "ARCHITECTURE.md"), "utf8");
    expect(run(["doc", root])).toContain("unchanged");
    expect(readFileSync(join(root, "ARCHITECTURE.md"), "utf8")).toBe(first);
  }, 120_000);

  it("--stdout prints and writes nothing", () => {
    const root = project();
    run(["index", root]);
    const output = run(["doc", root, "--stdout"]);
    expect(output).toContain("# Architecture");
    expect(existsSync(join(root, "ARCHITECTURE.md"))).toBe(false);
  }, 120_000);

  it("excludes all-test modules by default and includes them on request", () => {
    const root = project();
    mkdirSync(join(root, "tests/doc"), { recursive: true });
    writeFileSync(
      join(root, "tests/doc/render.test.ts"),
      "export function testRender() { return true; }\n",
    );
    run(["index", root]);

    const defaultOutput = run(["doc", root, "--stdout"]);
    expect(defaultOutput).not.toContain("| `tests/doc` |");
    expect(defaultOutput).toContain("--include-tests");

    const withTests = run([
      "doc",
      root,
      "--stdout",
      "--include-tests",
    ]);
    expect(withTests).toContain("| `tests/doc` |");
  }, 120_000);

  it("--check passes on a current file and fails on a stale one", () => {
    const root = project();
    run(["index", root]);
    run(["doc", root]);
    expect(run(["doc", root, "--check"])).toContain("up to date");
    writeFileSync(
      join(root, "ARCHITECTURE.md"),
      "<!-- generated by sonde doc; edits will be overwritten -->\nstale\n",
    );
    expect(run(["doc", root, "--check"], true)).toMatch(/out of date/i);
  }, 120_000);

  it("--module prints sorted detail without writing the committed document", () => {
    const root = project();
    run(["index", root]);
    const output = run(["doc", root, "--module", "src/b"]);
    expect(output).toContain("# Module `src/b`");
    expect(output).toContain("helper");
    expect(output).toContain("function");
    expect(output).toContain("`src/a`");
    expect(existsSync(join(root, "ARCHITECTURE.md"))).toBe(false);
  }, 120_000);

  it("refuses to overwrite a hand-written ARCHITECTURE.md", () => {
    const root = project();
    run(["index", root]);
    writeFileSync(join(root, "ARCHITECTURE.md"), "# My own notes\n");
    const output = run(["doc", root], true);
    expect(readFileSync(join(root, "ARCHITECTURE.md"), "utf8")).toBe(
      "# My own notes\n",
    );
    expect(output).toMatch(/--stdout/);
  }, 120_000);
});
