/**
 * Curated Apple SDK vocabulary observed by the Swift narrowing probe.
 *
 * This is deliberately conservative: classification only happens when the
 * repository contains no same-named declaration, but an uncertain name still
 * stays UNRESOLVED instead of being assigned a guessed framework.
 */
const symbolsByFramework: Readonly<Record<string, readonly string[]>> = {
  Swift: [
    "Any",
    "Array",
    "Bool",
    "CaseIterable",
    "Codable",
    "Dictionary",
    "Double",
    "Equatable",
    "Error",
    "Float",
    "Hashable",
    "Identifiable",
    "Int",
    "Never",
    "Sendable",
    "Set",
    "String",
    "Task",
    "UInt8",
    "UInt32",
    "UInt64",
    "Void",
    "abs",
    "allSatisfy",
    "append",
    "checkCancellation",
    "compactMap",
    "contains",
    "enumerated",
    "fatalError",
    "flatMap",
    "forEach",
    "hasPrefix",
    "joined",
    "max",
    "min",
    "print",
    "reduce",
    "removeAll",
    "removeFirst",
    "removeValue",
    "rounded",
    "split",
    "subtracting",
    "suffix",
    "uppercased",
    "withCheckedContinuation",
    "withCheckedThrowingContinuation",
    "withUnsafeBytes",
  ],
  SwiftUI: [
    "Binding",
    "Button",
    "Capsule",
    "Circle",
    "Color",
    "ContentUnavailableView",
    "DatePicker",
    "Divider",
    "EdgeInsets",
    "EmptyView",
    "ForEach",
    "Form",
    "GeometryReader",
    "GridItem",
    "Group",
    "HStack",
    "Image",
    "Label",
    "LazyVGrid",
    "LazyVStack",
    "LinearGradient",
    "List",
    "Menu",
    "NavigationLink",
    "NavigationStack",
    "Picker",
    "ProgressView",
    "Rectangle",
    "RoundedRectangle",
    "ScrollView",
    "ScrollViewReader",
    "Section",
    "Slider",
    "Spacer",
    "Stepper",
    "StrokeStyle",
    "TabView",
    "TextEditor",
    "TextField",
    "Toggle",
    "ToolbarItem",
    "VStack",
    "View",
    "ZStack",
    "accessibilityLabel",
    "alert",
    "animation",
    "bold",
    "buttonStyle",
    "clipShape",
    "confirmationDialog",
    "contentShape",
    "disabled",
    "environment",
    "fixedSize",
    "focused",
    "font",
    "fontWeight",
    "foregroundStyle",
    "frame",
    "ignoresSafeArea",
    "italic",
    "keyboardType",
    "kerning",
    "lineLimit",
    "lineSpacing",
    "listRowBackground",
    "listRowInsets",
    "minimumScaleFactor",
    "multilineTextAlignment",
    "navigationBarTitleDisplayMode",
    "navigationDestination",
    "navigationTitle",
    "onChange",
    "onTapGesture",
    "opacity",
    "overlay",
    "pickerStyle",
    "presentationDetents",
    "resizable",
    "rotationEffect",
    "safeAreaInset",
    "scaledToFit",
    "scrollContentBackground",
    "scrollTo",
    "shadow",
    "sheet",
    "stroke",
    "strokeBorder",
    "strikethrough",
    "swipeActions",
    "system",
    "tabItem",
    "tabViewStyle",
    "textInputAutocapitalization",
    "textSelection",
    "toolbar",
    "trim",
    "weight",
    "withAnimation",
  ],
  Foundation: [
    "Calendar",
    "Data",
    "Date",
    "DateComponents",
    "DateFormatter",
    "JSONDecoder",
    "JSONEncoder",
    "NSLock",
    "NSNumber",
    "NSPredicate",
    "NumberFormatter",
    "SortDescriptor",
    "TimeInterval",
    "TimeZone",
    "URL",
    "URLComponents",
    "URLQueryItem",
    "UUID",
    "addingTimeInterval",
    "archivedData",
    "base64EncodedString",
    "dateComponents",
    "isDateInToday",
    "isDate",
    "month",
    "removeObject",
    "stringArray",
    "timeIntervalSince",
    "trimmingCharacters",
    "unarchivedObject",
    "year",
  ],
  CoreGraphics: ["CGFloat", "CGRect", "CGSize"],
  CloudKit: [
    "CKContainer",
    "CKDatabase",
    "CKFetchRecordZoneChangesOperation",
    "CKQuerySubscription",
    "CKRecord",
    "CKRecordValue",
    "CKRecordZone",
    "CKRecordZoneSubscription",
    "CKShare",
    "deleteRecord",
    "modifyRecordZones",
    "modifyRecords",
  ],
  SwiftData: [
    "ModelConfiguration",
    "ModelContainer",
    "ModelContext",
    "Query",
    "fetch",
    "insert",
  ],
  CryptoKit: [
    "Curve25519",
    "KeyAgreement",
    "PrivateKey",
    "SealedBox",
    "SymmetricKey",
  ],
  CoreFoundation: ["CFTypeRef"],
  Security: ["SecItemAdd", "SecItemCopyMatching", "SecItemDelete"],
  CoreLocation: ["CLLocation", "CLLocationCoordinate2D"],
  BackgroundTasks: ["BGAppRefreshTaskRequest", "setTaskCompleted"],
  UIKit: [
    "UIImage",
    "UIGraphicsImageRenderer",
    "canOpenURL",
    "draw",
    "jpegData",
    "notificationOccurred",
  ],
  EventKit: ["EKEvent", "EKEventStore", "requestFullAccessToEvents"],
  HealthKit: ["HKHealthStore", "HKQuantityType", "isHealthDataAvailable"],
  UserNotifications: [
    "UNCalendarNotificationTrigger",
    "UNMutableNotificationContent",
    "UNNotificationRequest",
    "removePendingNotificationRequests",
  ],
  Speech: ["SFSpeechRecognizer"],
  OSLog: ["Logger"],
};

export const SWIFT_SDK_SYMBOLS: ReadonlyMap<string, string> = new Map(
  Object.entries(symbolsByFramework).flatMap(([framework, names]) =>
    names.map((name) => [name, framework] as const)
  ),
);
