import type { ModuleDependency, ModuleGraph } from "./modules.js";
import {
  compareDependencies,
  DIAGRAM_LIMIT,
  moduleOf,
  resolvedOf,
} from "./modules.js";

export { DIAGRAM_LIMIT } from "./modules.js";

/**
 * Nothing exhaustive belongs in the committed document (spec §4.3).
 *
 * The first dogfood shipped a complete dependency table of 277 rows and a
 * surface list 1,049 characters wide for one module. Both were technically
 * complete and neither was readable, which is the failure this document exists
 * to avoid. Completeness lives behind `sonde doc --module`.
 */
export const TABLE_LIMIT = 30;

/**
 * Strip the lines that report *state* rather than structure.
 *
 * The header stamps the commit the document describes, so committing the
 * document itself moves HEAD and changes the stamp — which would leave
 * `--check` permanently failing on a file nobody had to touch. The drift
 * warning is volatile for the same reason: it reflects the index, not the
 * architecture. `--check` asks whether the *structure* is stale, so it
 * compares everything except these.
 */
export function structuralBody(document: string): string {
  // Blank lines go too: this exists only for comparison, so removing a
  // volatile line must not leave whitespace behind that differs.
  return document
    .split("\n")
    .filter((line) =>
      line.trim() !== "" &&
      !line.startsWith("Describes ") &&
      !line.startsWith("> **") &&
      !line.endsWith("were excluded. Run `sonde doc --include-tests` to include them.")
    )
    .join("\n");
}
export const SURFACE_LIMIT = 6;

/** Allows the writer to distinguish Sonde output from a human-owned file. */
export const DOC_MARKER =
  "<!-- generated by sonde doc; edits will be overwritten -->";

export interface DocStamp {
  revision: string | null;
  dirty: boolean | null;
  driftedFiles: number;
  parseFailures: number;
}

function stampLine(stamp: DocStamp): string {
  if (stamp.revision === null) return "Describes an unversioned working tree.";
  const suffix = stamp.dirty === true
    ? " plus uncommitted changes"
    : stamp.dirty === null
      ? " (git state unknown)"
      : "";
  return `Describes commit ${stamp.revision}${suffix}.`;
}

/**
 * A dependency drawn dashed is real but thinly evidenced.
 *
 * Pairs with *no* resolved reference are not drawn at all, so testing for zero
 * resolved evidence here would be dead code. What the reader needs flagged is
 * the arrow that exists but rests mostly on name matching: `src/resolve` to
 * `src/adapters/typescript` carries 2 resolved references and 60 heuristic
 * ones, and should not look like `src/index` to `src/store`, which carries 41
 * resolved.
 */
function isInferred(dependency: ModuleDependency): boolean {
  return dependency.byTier.HEURISTIC > resolvedOf(dependency);
}

function evidence(dependency: ModuleDependency): string {
  return (["COMPILER", "LEXICAL", "HEURISTIC"] as const)
    .filter((tier) => dependency.byTier[tier] > 0)
    .map((tier) => `${tier} ${dependency.byTier[tier]}`)
    .join(", ");
}

function inlineCode(text: string): string {
  return `\`${text.replaceAll("|", "\\|")}\``;
}

export interface ModuleDetailSymbol {
  filePath: string;
  qualifiedName: string;
  shortName: string;
  kind: string;
}

export interface ModuleDetailEdge {
  srcFile: string;
  dstFile: string;
  dstName: string;
}

/** Render volatile symbol detail from plain rows; never committed to disk. */
export function renderModuleDetail(
  modulePath: string,
  symbols: ModuleDetailSymbol[],
  edges: ModuleDetailEdge[],
): string {
  const incoming = new Map<string, Set<string>>();
  for (const edge of edges) {
    if (moduleOf(edge.dstFile) !== modulePath) continue;
    const sourceModule = moduleOf(edge.srcFile);
    if (sourceModule === modulePath) continue;
    const sources = incoming.get(edge.dstName);
    if (sources) sources.add(sourceModule);
    else incoming.set(edge.dstName, new Set([sourceModule]));
  }

  const selected = symbols
    .filter(({ filePath }) => moduleOf(filePath) === modulePath)
    .sort((left, right) => {
      const leftKey = `${left.shortName}\u0000${left.qualifiedName}\u0000${left.filePath}`;
      const rightKey = `${right.shortName}\u0000${right.qualifiedName}\u0000${right.filePath}`;
      return leftKey === rightKey ? 0 : leftKey < rightKey ? -1 : 1;
    });

  const lines = [`# Module ${inlineCode(modulePath)}`, ""];
  if (selected.length === 0) {
    lines.push("No indexed symbols were found for this module.", "");
    return lines.join("\n");
  }

  lines.push(
    "| Symbol | Kind | File | Referenced by modules |",
    "|---|---|---|---|",
  );
  for (const symbol of selected) {
    const referencedBy = [...(incoming.get(symbol.shortName) ?? [])]
      .sort()
      .map(inlineCode)
      .join(", ") || "—";
    lines.push(
      `| ${inlineCode(symbol.qualifiedName)} | ${symbol.kind} | ` +
        `${inlineCode(symbol.filePath)} | ${referencedBy} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** Pure ModuleGraph-to-Markdown rendering; no clock, I/O, or ambient paths. */
export function renderDoc(graph: ModuleGraph, stamp: DocStamp): string {
  const lines: string[] = ["# Architecture", "", DOC_MARKER, ""];
  const dependencies = [...graph.dependencies].sort(compareDependencies);
  const total =
    graph.tierTotals.COMPILER +
    graph.tierTotals.LEXICAL +
    graph.tierTotals.HEURISTIC;
  const moduleIds = new Map(
    graph.modules.map(({ path }, index) => [path, `m${index}`]),
  );
  const idFor = (path: string): string => {
    const id = moduleIds.get(path);
    if (id === undefined) {
      throw new Error(`dependency references absent module: ${path}`);
    }
    return id;
  };

  lines.push(stampLine(stamp), "");
  if (graph.excludedTestModules > 0) {
    lines.push(
      `${graph.excludedTestModules} all-test module(s) were excluded. ` +
        "Run `sonde doc --include-tests` to include them.",
      "",
    );
  }
  if (stamp.driftedFiles > 0) {
    lines.push(
      `> **${stamp.driftedFiles} file(s) differ from the index used for this ` +
        "document.** Run `sonde index`, then `sonde doc` to refresh.",
      "",
    );
  }
  if (stamp.parseFailures > 0) {
    lines.push(
      `> **${stamp.parseFailures} file(s) did not parse cleanly**, so their ` +
        "symbols may be missing here.",
      "",
    );
  }

  lines.push(
    "Cross-module references by how they were resolved: " +
      `COMPILER ${graph.tierTotals.COMPILER}, ` +
      `LEXICAL ${graph.tierTotals.LEXICAL}, ` +
      `HEURISTIC ${graph.tierTotals.HEURISTIC}.`,
    "",
    "`HEURISTIC` means the target was inferred from a name rather than " +
      "resolved. Dependencies supported only by heuristic references are " +
      "drawn with dashed arrows and should be read as likely, not certain." +
      (graph.tierTotals.COMPILER === 0
        ? " Run `sonde index --resolve` for compiler-resolved edges."
        : ""),
    "",
    "## Module dependencies",
    "",
  );

  if (dependencies.length === 0) {
    lines.push("No cross-module references were found.", "");
  } else {
    lines.push("```mermaid", "graph LR");
    const verified = dependencies.filter(
      (dep) => resolvedOf(dep) > 0,
    );
    for (const dependency of verified.slice(0, DIAGRAM_LIMIT)) {
      const arrow = isInferred(dependency) ? "-.->" : "-->";
      lines.push(
        `  ${idFor(dependency.from)}[${JSON.stringify(dependency.from)}] ` +
          `${arrow}|${resolvedOf(dependency)}| ` +
          `${idFor(dependency.to)}[${JSON.stringify(dependency.to)}]`,
      );
    }
    lines.push("```", "");
    const omittedDependencies = Math.max(
      graph.omittedDependencies,
      dependencies.length - DIAGRAM_LIMIT,
    );
    if (omittedDependencies > 0) {
      lines.push(
        `${omittedDependencies} lower-weight dependency pair(s) are not shown ` +
          "in the diagram; the table below is complete.",
        "",
      );
    }
    lines.push(
      "| From | To | References | Evidence |",
      "|---|---|---:|---|",
    );
    for (const dependency of verified.slice(0, TABLE_LIMIT)) {
      lines.push(
        `| ${inlineCode(dependency.from)} | ${inlineCode(dependency.to)} | ` +
          `${dependency.total} | ${evidence(dependency)} |`,
      );
    }
    const untabled = verified.length - TABLE_LIMIT;
    if (untabled > 0) {
      lines.push(
        "",
        `${untabled} lighter ${untabled === 1 ? "dependency is" : "dependencies are"} ` +
          "not listed. Run `sonde doc --module <path>` for a module's complete set.",
      );
    }
    if (graph.unverifiedPairs > 0) {
      lines.push(
        `${graph.unverifiedPairs} further module pair(s) share symbol names but ` +
          "have no resolved reference between them. They are not shown: a shared " +
          "name is a coincidence, not a dependency, and modules with parallel " +
          "structure produce the most of them.",
        "",
      );
    }
    lines.push("");
  }

  lines.push(
    "## Modules",
    "",
    "| Module | Files | Symbols | Used by other modules |",
    "|---|---:|---:|---|",
  );
  for (const module of graph.modules) {
    // Ranked by reference count upstream, so the shown names are the ones
    // other modules actually lean on.
    const shown = module.surface.slice(0, SURFACE_LIMIT).map(inlineCode);
    const hidden = module.surface.length - shown.length;
    const surface = module.surface.length === 0
      ? "—"
      : shown.join(", ") + (hidden > 0 ? `, +${hidden} more` : "");
    lines.push(
      `| ${inlineCode(module.path)} | ${module.files} | ${module.symbols} | ` +
        `${surface} |`,
    );
  }
  lines.push(
    "",
    "Symbol-level detail is not committed, because it changes on every edit. " +
      "Run `sonde doc --module <path>` for it.",
    "",
  );
  if (total === 0) lines.push("No references were indexed.", "");

  return lines.join("\n");
}
