import type { ModuleDependency, ModuleGraph } from "./modules.js";

/** Allows the writer to distinguish Sonde output from a human-owned file. */
export const DOC_MARKER =
  "<!-- generated by sonde doc; edits will be overwritten -->";

export interface DocStamp {
  revision: string | null;
  dirty: boolean | null;
  driftedFiles: number;
  parseFailures: number;
}

function stampLine(stamp: DocStamp): string {
  if (stamp.revision === null) return "Describes an unversioned working tree.";
  const suffix = stamp.dirty === true
    ? " plus uncommitted changes"
    : stamp.dirty === null
      ? " (git state unknown)"
      : "";
  return `Describes commit ${stamp.revision}${suffix}.`;
}

function isInferred(dependency: ModuleDependency): boolean {
  return (
    dependency.byTier.COMPILER === 0 && dependency.byTier.LEXICAL === 0
  );
}

function evidence(dependency: ModuleDependency): string {
  return (["COMPILER", "LEXICAL", "HEURISTIC"] as const)
    .filter((tier) => dependency.byTier[tier] > 0)
    .map((tier) => `${tier} ${dependency.byTier[tier]}`)
    .join(", ");
}

function inlineCode(text: string): string {
  return `\`${text.replaceAll("|", "\\|")}\``;
}

/** Pure ModuleGraph-to-Markdown rendering; no clock, I/O, or ambient paths. */
export function renderDoc(graph: ModuleGraph, stamp: DocStamp): string {
  const lines: string[] = ["# Architecture", "", DOC_MARKER, ""];
  const total =
    graph.tierTotals.COMPILER +
    graph.tierTotals.LEXICAL +
    graph.tierTotals.HEURISTIC;
  const moduleIds = new Map(
    graph.modules.map(({ path }, index) => [path, `m${index}`]),
  );
  const idFor = (path: string): string => {
    const id = moduleIds.get(path);
    if (id === undefined) {
      throw new Error(`dependency references absent module: ${path}`);
    }
    return id;
  };

  lines.push(stampLine(stamp), "");
  if (stamp.driftedFiles > 0) {
    lines.push(
      `> **${stamp.driftedFiles} file(s) differ from the index used for this ` +
        "document.** Run `sonde index`, then `sonde doc` to refresh.",
      "",
    );
  }
  if (stamp.parseFailures > 0) {
    lines.push(
      `> **${stamp.parseFailures} file(s) did not parse cleanly**, so their ` +
        "symbols may be missing here.",
      "",
    );
  }

  lines.push(
    "Cross-module references by how they were resolved: " +
      `COMPILER ${graph.tierTotals.COMPILER}, ` +
      `LEXICAL ${graph.tierTotals.LEXICAL}, ` +
      `HEURISTIC ${graph.tierTotals.HEURISTIC}.`,
    "",
    "`HEURISTIC` means the target was inferred from a name rather than " +
      "resolved. Dependencies supported only by heuristic references are " +
      "drawn with dashed arrows and should be read as likely, not certain." +
      (graph.tierTotals.COMPILER === 0
        ? " Run `sonde index --resolve` for compiler-resolved edges."
        : ""),
    "",
    "## Module dependencies",
    "",
  );

  if (graph.dependencies.length === 0) {
    lines.push("No cross-module references were found.", "");
  } else {
    lines.push("```mermaid", "graph LR");
    for (const dependency of graph.dependencies) {
      const arrow = isInferred(dependency) ? "-.->" : "-->";
      lines.push(
        `  ${idFor(dependency.from)}[${JSON.stringify(dependency.from)}] ` +
          `${arrow}|${dependency.total}| ` +
          `${idFor(dependency.to)}[${JSON.stringify(dependency.to)}]`,
      );
    }
    lines.push("```", "");
    lines.push(
      "| From | To | References | Evidence |",
      "|---|---|---:|---|",
    );
    for (const dependency of graph.dependencies) {
      lines.push(
        `| ${inlineCode(dependency.from)} | ${inlineCode(dependency.to)} | ` +
          `${dependency.total} | ${evidence(dependency)} |`,
      );
    }
    lines.push("");
  }

  lines.push(
    "## Modules",
    "",
    "| Module | Files | Symbols | Used by other modules |",
    "|---|---:|---:|---|",
  );
  for (const module of graph.modules) {
    const surface = module.surface.length === 0
      ? "—"
      : module.surface.map(inlineCode).join(", ");
    lines.push(
      `| ${inlineCode(module.path)} | ${module.files} | ${module.symbols} | ` +
        `${surface} |`,
    );
  }
  lines.push(
    "",
    "Symbol-level detail is not committed, because it changes on every edit. " +
      "Run `sonde doc --module <path>` for it.",
    "",
  );
  if (total === 0) lines.push("No references were indexed.", "");

  return lines.join("\n");
}
